<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);SA1501;SA1513;SA1516;SA1518;SA1407;SA1412;SA1633;SA1313;CA2000;CA1305;CA2234;CS8632</NoWarn>
  </PropertyGroup>
  <Import Project="..\PowerFxBuild.props" />
  <PropertyGroup>
    <NoWarn>$(NoWarn);1701;1702;1998;NU1605;SA1513;SA1515;SA1516</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CdpHelpers\CdpHelpers.csproj" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <!-- Extra data handlers -->
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>
